-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."transactions" add column "block_time" bigint
--  not null unique;
