package config

import (
	"log"
	"os"

	"github.com/go-jose/go-jose/v4"
	"github.com/joho/godotenv"
)

var (
	SEPOLIA_URL          = ""
	INFURA_PROJECT_ID    = ""
	SEPOLIA_URL_HTTP     = "https://sepolia.infura.io/v3/"
	REDIS_SECRET         = ""
	REDIS_URL            = "redis://localhost:6379"
	INFURA_SEPOLIA_URL   = ""
	BTC_RPC_USER         = "user"
	BTC_RPC_PASS         = "pass"
	BTC_RPC_HOST         = "localhost:8332"
	BTC_RPC_PORT         = "8332"
	BTC_POST_MODE        = true
	AUTH_JWT_PUBLIC_KEY  = "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqx+7XJxJR+0Lp8hLFKYr5Gc+0RPIdaZJ18GH8b//oMn7PCVe0gLQDkxjvhKo2ySMgWSOSGaNJkZXLhN4jlot/xaulN3dSbrgQPxvx3ALd3nXJaTLOb7xBODd196r+Ylg1QPICdrBQVi6qAXacq/UBK8K7BWQ0TG2/R9aB5mNSGtY3Ogj9xp2MP5LTi7f2Alj6IwSFRN+9SCmH3NiQzNUPBWJB02Lgx1oxwtfevkQ3BpwIqzkOTTE1G7PXgKbYRBUlUNqwvMIjk89tRf/qHgMbRPGYYNu7XoRt8AOVgNFUcL51Gb9vM75XstWoAh6BwYQsceEXUU7dgIJem9zItFRdwIDAQAB-----END PUBLIC KEY-----"
	AUTH_JWT_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrH7tcnElH7QunyEsUpivkZz7RE8h1pknXwYfxv/+gyfs8JV7SAtAOTGO+EqjbJIyBZI5IZo0mRlcuE3iOWi3/Fq6U3d1JuuBA/G/HcAt3edclpMs5vvEE4N3X3qv5iWDVA8gJ2sFBWLqoBdpyr9QErwrsFZDRMbb9H1oHmY1Ia1jc6CP3GnYw/ktOLt/YCWPojBIVE371IKYfc2JDM1Q8FYkHTYuDHWjHC196+RDcGnAirOQ5NMTUbs9eApthEFSVQ2rC8wiOTz21F/+oeAxtE8Zhg27tehG3wA5WA0VRwvnUZv28zvley1agCHoHBhCxx4RdRTt2Agl6b3Mi0VF3AgMBAAECggEAMom1kN1LOyXDynJ50ghdcCAZyi+YhT5uEn1Cg+AbQ8ZDH3k97rIL9h0TXAAwxD+gC1rCNpmq2AHwH1h6wzfY27w8JRT9FJhPQIINFQ5/JHLkWma36j78+V7bxbQqgBDVezOZsWdcqcrlnVfVMwfAiv2TMTQRR+bxzwGiWho8QoWNq1UcA8GGOE3vzWGrZJbgVwG43xUVDJtMem9w4QwlHLwekP3Q46Lqx1AOtesN39h/HduJtWtYGcw/t2TkIW9UibmBqZy7rkZW+4hCXhGBI6YhAUYnuyP6ZT+r1+J2aPlJeo2yIyjc6YVxoFwUR7QWtINzuBtG9v/YXfmtYCnEIQKBgQDd3E/nX4Vc7xolvoQZzN+0XWnyLqPgtAL63RLFfb8/lhnHHzca2k2eI0+P6I9etDa9c+i4l7/RM5LUkwxd8RGH6S4m8FiUkdKyaiwK1PAGRiUbWaij9WjKVjp7QhEtisQvtyMa9quwpv3C02zbD31/PqgeTmXOH0Aweh162qyeBwKBgQDFdMQ13JCkQe3GNO06EEPE+NjFkLqBVP2leDXmUVZRnHUN4OMpjCb9H0+/4rOAusCRmS9kALoeo6U9ykC5mqUViVzeTqnHXctD4llvEzSngDU/4+cbUQG3obj8JG9lupe/p3r6gRvB13nWiwVzj2wgK2SY0HGG1gaRaIS3K2nVEQKBgQCNhlJ6V9as9+GIHkYKZ0R0u/ovgU0MtAgKmye0T4jGOSvsd58hRAyrSf8g38tFMFSS+fOEfVjhTLLnY35KFtOGDVthf4QiEfuD0HKT3k3W0rws/D61iID2QZdAtV5b3N9VSM/eDWhsYboSo+gWvYTivMdlvcD3gbvisKNJkWD31QKBgCdgIqSPCHUJBK6K7WevyKPl7+xt8RNLbI1rzGvSeoEpzxnmZ8ZoQXomnVOplJwuIaqnPpEVqAfmIFSTGZcppJQH4XIfg7HTHW67G5SP4ucoJPZJr1N+MvZ4lJgLd/90V0CL2HVN+8gK/SvwazThO/GqVZQ3tPvrgEHM8vJIAQHRAoGAEjFMNmitScLogo9Cq5oX88/KpDOfCi+IG19g0HdaepgzreDzallcKf/XnXX9d7wuTuoSRNsq7RfCmLAUlzC+Waw0dpwLkZjgeVvFdrADGOFDKEovesZ0NBQ+Ln0SXJVRaynRxgnrjYINE+1I3uE8XZie4NMh5pybTXBpyx/cIz0=-----END PRIVATE KEY-----"
)

const (
	JWT_ALG    = jose.RS256
	CLIENT_URL = "http://localhost:3000"
	PORT       = 8085
	KAFKA_URL  = "localhost:9092"
	KAFKA_TXN_TOPIC = "txn4"
)

func init() {
	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}

	if ENV_SEPOLIA_URL := os.Getenv("SEPOLIA_URL"); ENV_SEPOLIA_URL != "" {
		SEPOLIA_URL = ENV_SEPOLIA_URL
	}
	if ENV_INFURA_PROJECT_ID := os.Getenv("INFURA_PROJECT_ID"); ENV_INFURA_PROJECT_ID != "" {
		INFURA_PROJECT_ID = ENV_INFURA_PROJECT_ID
	}
	if ENV_SEPOLIA_URL_HTTP := os.Getenv("SEPOLIA_URL_HTTP"); ENV_SEPOLIA_URL_HTTP != "" {
		SEPOLIA_URL_HTTP = ENV_SEPOLIA_URL_HTTP
		INFURA_SEPOLIA_URL = SEPOLIA_URL_HTTP + INFURA_PROJECT_ID
	}
	if ENV_REDIS_SECRET := os.Getenv("REDIS_SECRET"); ENV_REDIS_SECRET != "" {
		REDIS_SECRET = ENV_REDIS_SECRET
	}
	if ENV_REDIS_URL := os.Getenv("REDIS_URL"); ENV_REDIS_URL != "" {
		REDIS_URL = ENV_REDIS_URL
	}
	if ENV_BTC_RPC_USER := os.Getenv("BTC_RPC_USER"); ENV_BTC_RPC_USER != "" {
		BTC_RPC_USER = ENV_BTC_RPC_USER
	}
	if ENV_BTC_RPC_PASS := os.Getenv("BTC_RPC_PASS"); ENV_BTC_RPC_PASS != "" {
		BTC_RPC_PASS = ENV_BTC_RPC_PASS
	}
	if ENV_BTC_RPC_HOST := os.Getenv("BTC_RPC_HOST"); ENV_BTC_RPC_HOST != "" {
		BTC_RPC_HOST = ENV_BTC_RPC_HOST
	}
	if ENV_BTC_RPC_PORT := os.Getenv("BTC_RPC_PORT"); ENV_BTC_RPC_PORT != "" {
		BTC_RPC_PORT = ENV_BTC_RPC_PORT
	}
	if ENV_AUTH_JWT_PUBLIC_KEY := os.Getenv("AUTH_JWT_PUBLIC_KEY"); ENV_AUTH_JWT_PUBLIC_KEY != "" {
		AUTH_JWT_PUBLIC_KEY = ENV_AUTH_JWT_PUBLIC_KEY
	}
	if ENV_AUTH_JWT_PRIVATE_KEY := os.Getenv("AUTH_JWT_PRIVATE_KEY"); ENV_AUTH_JWT_PRIVATE_KEY != "" {
		AUTH_JWT_PRIVATE_KEY = ENV_AUTH_JWT_PRIVATE_KEY
	}
}
