-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."client" add column "address" jsonb
--  not null default jsonb_build_array();
